# Generated by Django 5.2 on 2025-05-05 03:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalouge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('file', models.FileField(upload_to='catalouges/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CatalaougeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='catalouge/images/')),
                ('page', models.PositiveSmallIntegerField(default=1)),
                ('catalouge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='generals.catalouge')),
            ],
            options={
                'ordering': ('page',),
            },
        ),
    ]
