# Generated by Django 5.2 on 2025-05-05 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catalouge',
            new_name='Catalogue',
        ),
        migrations.RenameModel(
            old_name='CatalaougeImage',
            new_name='CatalogueImage',
        ),
    ]
