# Generated by Django 5.2 on 2025-05-05 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0002_rename_catalouge_catalogue_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogueimage',
            old_name='catalouge',
            new_name='catalogue',
        ),
        migrations.AlterField(
            model_name='catalogue',
            name='file',
            field=models.FileField(upload_to='catalogues/'),
        ),
        migrations.AlterField(
            model_name='catalogueimage',
            name='image',
            field=models.ImageField(upload_to='catalogue/images/'),
        ),
    ]
