# Generated by Django 5.2 on 2025-05-05 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generals', '0003_rename_catalouge_catalogueimage_catalogue_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogue',
            name='quality',
            field=models.PositiveSmallIntegerField(default=85),
        ),
        migrations.AddField(
            model_name='catalogue',
            name='resolution',
            field=models.PositiveSmallIntegerField(default=150),
        ),
    ]
